# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

version: 1.3.0.{build}

Add-Type -assembly "system.io.compression.filesystem"

Write-Host "Downloading boost.."
(new-object net.webclient).DownloadFile("http://bit.ly/1JPHkL3&quot;, "C:\boost_1_59_0.zip")
Write-Host "Extracting archive.."
[io.compression.zipfile]::ExtractToDirectory("C:\boost_1_59_0.zip", "C:\")
Set-Location "C:\boost_1_59_0"
Write-Host "Building boost.."
& ".\bootstrap.bat"

# & .\b2 address-model=64 toolset=msvc-14.0 windows-api=desktop variant=debug link=static threading=multi runtime-link=shared --with-log

& .\b2 address-model=64 architecture=x86 --build-type=complete
& .\b2 install --prefix="c:\libraries\x64"
