# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

version: 1.3.0.{build}

environment:
  BOOST_ROOT: C:\Libraries\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost\lib32-msvc-12.0
  matrix:
  - VS_GEN: Visual Studio 12 2013
    CONFIG: Release
    B_NAME: Windows-x86
#  - VS_GEN: Visual Studio 12 2013 Win64
#    CONFIG: Release
#    B_NAME: Windows-x86_64

# scripts that are called at very beginning, before repo cloning
init:
  # Print environment info ( set / systeminfo)
  - msbuild /version
  - cmake --version
  - python --version
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - choco install activetcl
  - choco install pandoc
  
before_build:
  - cmake -Wno-dev -G"%VS_GEN%" -DCMAKE_BUILD_TYPE=%CONFIG% -DVERA_USE_SYSTEM_LUA=OFF
  
# Uncomment below if you want to debug via RDP
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
